# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Integrate"

on:
  push:
    branches:
      - "master"
  pull_request: null
  # Add [skip ci] to commit message to skip CI.

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  run-all:
    name: "Run all checks"
    runs-on: "ubuntu-24.04"
    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.5"
    steps:
      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"

      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v3"

      - run: "composer run all"
